### ISSUE TITLE
todo：界面美化

### ISSUE THREAD

**Issue by yltx** [yltx/vscode-luogu-developer#41]
需要美化的界面：

- [ ] 1. 题单：添加区域式阴影，加上深色模式（具体参考题解）

- [x] 2. 比赛：将长方形的tag改为椭圆形，修复区域式阴影显示不正常的问题，加上深色模式

- [ ] 3. 所有界面都不同程度的存在大量无用代码。我没有能力分辨出来哪些是有用的，所以等待懂html的大佬进行一个删除。

**Comment by yltx** [comment]
> *This was generated by AI during triage.*

Completed across the frontend cleanup work and merged PR #187. Training list/details now have theme-aware card/table styling, shadows, dark-theme support and responsive layouts; contest and solution views were also refreshed, and obsolete frontend code was removed during the cleanup refactors.
